In [2]:
import pandas as pd
import numpy as np
import keras.models
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

In [3]:
data=load_breast_cancer()

In [4]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [6]:
print(data['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [7]:
print(data['target_names'])
print(data['filename'])

['malignant' 'benign']
/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/breast_cancer.csv


In [8]:
pd.DataFrame(data['data'],columns=data['feature_names'])

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [9]:
feature=data['data']
label=data['target']

In [10]:
scaling=StandardScaler()
feature=scaling.fit_transform(feature)

In [11]:
pd.DataFrame(feature,columns=data['feature_names'])

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0       1.097064     -2.073335  ...        2.750622                 1.937015
1       1.829821     -0.353632  ...       -0.243890                 0.281190
2       1.579888      0.456187  ...        1.152255                 0.201391
3      -0.768909      0.253732  ...        6.046041                 4.935010
4       1.750297     -1.151816  ...       -0.868353                -0.397100
..           ...           ...  ...             ...                      ...
564     2.110995      0.721473  ...       -1.360158                -0.709091
565     1.704854      2.085134  ...       -0.531855                -0.973978
566     0.702284      2.045574  ...       -1.104549                -0.318409
567     1.838341      2.336457  ...        1.919083                 2.219635
568    -1.808401      1.221792  ...       -0.048138                -0.751207

[569 rows x 30 columns]

In [12]:
feature.shape

(569, 30)

In [13]:
X_train=feature[:500]
X_test=feature[500:535]
X_val=feature[535:]
y_train=label[:500]
y_test=label[500:535]
y_val=label[535:]

In [14]:
model= Sequential()
model.add(Dense(15,activation='relu',input_dim=30))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy']) 

In [15]:
model.fit(X_train,y_train,epochs=10,batch_size=5,validation_split=.1)

Epoch 1/10
90/90 [==============================] - 1s 4ms/step - loss: 0.5948 - accuracy: 0.6333 - val_loss: 0.5719 - val_accuracy: 0.7000
Epoch 2/10
90/90 [==============================] - 0s 2ms/step - loss: 0.3638 - accuracy: 0.9556 - val_loss: 0.3329 - val_accuracy: 0.9000
Epoch 3/10
90/90 [==============================] - 0s 2ms/step - loss: 0.1736 - accuracy: 0.9756 - val_loss: 0.1935 - val_accuracy: 0.9200
Epoch 4/10
90/90 [==============================] - 0s 2ms/step - loss: 0.1055 - accuracy: 0.9800 - val_loss: 0.1508 - val_accuracy: 0.9600
Epoch 5/10
90/90 [==============================] - 0s 2ms/step - loss: 0.0812 - accuracy: 0.9822 - val_loss: 0.1319 - val_accuracy: 0.9600
Epoch 6/10
90/90 [==============================] - 0s 2ms/step - loss: 0.0694 - accuracy: 0.9822 - val_loss: 0.1181 - val_accuracy: 0.9600
Epoch 7/10
90/90 [==============================] - 0s 2ms/step - loss: 0.0622 - accuracy: 0.9822 - val_loss: 0.1127 - val_accuracy: 0.9400
Epoch 8/10
90/90 [==

In [16]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.0670 - accuracy: 0.9714


[0.06697618216276169, 0.9714285731315613]

In [19]:
for i in range(10):
  test=np.reshape(X_val[i],(1,30))
  if(float(model.predict(test)[0][0])>0.5):
    print('-bening')
  else:
    print('-malignant')
  if(y_val[i]>0.5):
    print('*Bening')
  else:
    print('*Malignant')
  print('--------------')

-malignant
*Malignant
--------------
-malignant
*Malignant
--------------
-bening
*Bening
--------------
-bening
*Bening
--------------
-bening
*Bening
--------------
-bening
*Bening
--------------
-malignant
*Bening
--------------
-bening
*Bening
--------------
-bening
*Bening
--------------
-bening
*Bening
--------------
